### Register a new user
POST localhost:3330/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Harrison Ernser",
  "email": "whitney.moss@example.com",
  "password": "123456"
}

### Login as a user
POST localhost:3330/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "whitney.moss@example.com",
  "password": "123456"
}

### Login as an admin
POST localhost:3330/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "abby.montgomery@example.com",
  "password": "123456"
}

### Check a user
GET localhost:3330/api/auth/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiYWJieS5tb250Z29tZXJ5QGV4YW1wbGUuY29tIiwibmFtZSI6IlpvaWxhIERpY2tpIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjc2MzgxMTYzLCJleHAiOjE2NzYzODIwNjN9.j1AzZ8Dh3QsL8VRPESHP4-r_L7oQwreuY8bLJsC1RfE
