### Register a new user
POST localhost:3330/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Harrison Ernser",
  "email": "whitney.moss@example.com",
  "password": "123456"
}

### Login a user
POST localhost:3330/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "whitney.moss@example.com",
  "password": "123456"
}

### Get a user
GET localhost:3330/api/auth/1 HTTP/1.1
