### Get shop items  list
GET localhost:3330/api/item?sort=rating HTTP/1.1

### Get shop items filtered list
GET localhost:3330/api/item?sort=price&direction=asc&type=electric&strings=6&limit=2&page=2 HTTP/1.1

### Get a shop item
GET localhost:3330/api/item/3 HTTP/1.1

### Create a new shop item — admin
POST localhost:3330/api/item HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiYWJieS5tb250Z29tZXJ5QGV4YW1wbGUuY29tIiwibmFtZSI6IlpvaWxhIERpY2tpIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjc1ODczNDk5LCJleHAiOjE2NzU4NzQzOTl9.luTbb2jHihxYN8fPymjfl7RPke_Rj5jvuf11texMkys

{
  "name": "Gibson Les Paul Traditional Pro V",
  "description": "The Gibson Trad Pro V electric guitar shares the same DNA as a Les Paul—mahogany body and neck, carved maple top—but it's also a completely evolved instrument. You'll feel it first: The body is weight-relieved, making it super comfortable to sling on the shoulder. The neck has an asymmetrical shape that fits like a glove. Thanks to the compound radius rosewood fretboard, you'll find it easier to solo in higher registers. And that's where you'll hear the difference, too.",
  "photo": "gibson-1.jpg",
  "type": "Electric",
  "code": "1500000000287968",
  "stringsNumber": 6,
  "price": 2399
}

### Update a shop item — admin
PATCH localhost:3330/api/item/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiYWJieS5tb250Z29tZXJ5QGV4YW1wbGUuY29tIiwibmFtZSI6IlpvaWxhIERpY2tpIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjc1ODczNDk5LCJleHAiOjE2NzU4NzQzOTl9.luTbb2jHihxYN8fPymjfl7RPke_Rj5jvuf11texMkys

{
  "name": "Schecter Guitar Research C-1",
  "code": "234523452345"
}

### Create a comment for the shop item — auth user
POST localhost:3330/api/item/4/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoid2hpdG5leS5tb3NzQGV4YW1wbGUuY29tIiwibmFtZSI6IlRlbmEgSGVhdGhjb3RlIiwiaXNBZG1pbiI6ZmFsc2UsImlhdCI6MTY3NTg3NDY0OSwiZXhwIjoxNjc1ODc1NTQ5fQ.tveElhf7jUf3wN9438CWf7yS8PtjRW9Y0_36ZnfuAPg

{
  "advantages": "Good feel, fun to play, good tone, solid electronics, good pick up",
  "disadvantages": "Fret buzz, flat sound, no pick, no dip switch sticker, and nut is off, poor fitting knob",
  "text": "So in the 30 years I have been playing I have owned 5 Les Pauls and have played more than can be counted. I have always had love hate relationship with Les Pauls. I love the look, love the sound. However, I always hated the necks, too thick and sticky. Also they are incredibly heavy.",
  "rating": 3
}

### Get the item comments
GET localhost:3330/api/item/2/comments

### Delete an item — admin
DELETE localhost:3330/api/item/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiYWJieS5tb250Z29tZXJ5QGV4YW1wbGUuY29tIiwibmFtZSI6IlpvaWxhIERpY2tpIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjc1ODczNDk5LCJleHAiOjE2NzU4NzQzOTl9.luTbb2jHihxYN8fPymjfl7RPke_Rj5jvuf11texMkys
